"""Write a local MediaMTX config from AI_CAMERA_* in .env.

The generated file contains RTSP passwords. It is gitignored.
Run from the repository root:

    python scripts/write_mediamtx_config.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "hardware" / "ai_parking"))

from camera_registry import load_cameras  # noqa: E402
from load_env import load_project_env  # noqa: E402


def mediamtx_path(camera_id: str) -> str:
    """Must match App\\Services\\WebRtcStream::pathFor."""
    slug = "".join(ch if ch.isalnum() else "-" for ch in camera_id.lower())
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug.strip("-")


def rtsp_source(camera) -> str:
    user = quote(camera.user, safe="")
    password = quote(camera.password, safe="")
    path = camera.preview_path if camera.preview_path.startswith("/") else "/" + camera.preview_path
    return f"rtsp://{user}:{password}@{camera.ip}:{camera.port}{path}"


def yaml_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> int:
    load_project_env()
    cameras = [cam for cam in load_cameras(ROOT / "hardware" / "ai_parking") if cam.enabled and cam.ip and cam.has_credentials]
    if not cameras:
        print("No enabled cameras with an IP and password were found in .env.")
        return 1

    hosts = [part.strip() for part in os.getenv("MEDIAMTX_WEBRTC_ADDITIONAL_HOSTS", "127.0.0.1").split(",") if part.strip()]
    origin = os.getenv("MEDIAMTX_WEBRTC_ALLOW_ORIGIN", "*").strip() or "*"
    out = ROOT / "storage" / "app" / "mediamtx" / "mediamtx.yml"
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Generated by scripts/write_mediamtx_config.py. Do not commit.",
        "# MediaMTX 1.11.x. Browser video only. YOLO keeps its own RTSP connection.",
        "logLevel: info",
        "rtsp: no",
        "rtmp: no",
        "hls: no",
        "srt: no",
        "webrtc: yes",
        "webrtcAddress: :8889",
        "webrtcEncryption: no",
        "webrtcAllowOrigin: " + yaml_quote(origin),
        "webrtcAdditionalHosts:",
    ]
    for host in hosts:
        lines.append("  - " + yaml_quote(host))
    lines.append("paths:")
    for camera in cameras:
        path = mediamtx_path(camera.camera_id)
        lines.extend([
            f"  {path}:",
            "    source: " + yaml_quote(rtsp_source(camera)),
            "    rtspTransport: " + yaml_quote(camera.rtsp_transport or "tcp"),
            "    sourceOnDemand: yes",
        ])
        print(f"{camera.camera_id} -> {path} ({camera.ip}, preview, password hidden)")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
